"""Bare-minimum builder input — Python form.

Mirror of ``bare_minimum.yaml``. The smallest legal config:
``about``, ``unit``, ``window``, ``metrics`` (>=1), ``segments`` (>=1).
Everything else is auto-generated by the interpreter (``dim_date``,
``dim_{unit}``, ``fct_{unit}`` carrying every metric).

Run:
    >>> from plotsim.configs.new.bare_minimum import config
    >>> from plotsim import generate_tables
    >>> tables = generate_tables(config)
"""
from plotsim import create

config = create(
    about="Subscription customers",
    unit="customer",
    seed=42,                               # pin determinism

    window=("2024-01", "2024-12", "monthly"),

    metrics=[
        {"name": "engagement", "type": "score", "polarity": "positive"},
        {"name": "payments",   "type": "count", "polarity": "positive"},
    ],

    segments=[
        {"name": "active",   "count": 50, "archetype": "growth"},
        {"name": "inactive", "count": 30, "archetype": "decline"},
    ],
)
