"""Customer reviews — Python-shaped narrative-text template.

This is the ``create(**kwargs)`` mirror of ``narrative_reviews.yaml`` —
both produce identical engine configs given the same seed. Pick whichever
surface fits your workflow:

* ``narrative_reviews.yaml`` for config-as-data fixtures checked into git
* this file for code-shaped configs that compose with regular Python

Showcase template for ``NarrativeSource`` columns:

  * ``fct_reviews.review_text`` is a trajectory- and archetype-driven
    sentence generated by sampling slot phrases from a per-archetype
    lexicon. Each cell is built from
    ``(trajectory_position, archetype, RNG_state)``: same seed →
    byte-identical text.
  * Three segments (``promoters``, ``neutrals``, ``detractors``) ride
    three archetypes (growth / flat / decline). Bands carry a
    **universal sentiment gradient** — low = negative language, mid =
    neutral language, high = positive language — consistent across all
    three archetypes. A growth entity's text becomes more positive as
    the trajectory rises; a decline entity's text becomes more negative.
  * Each slot is an independent aspect: ``opener`` is archetype-
    distinct (the segment's speaking style), while ``object`` and
    ``comment`` share sentiment vocabulary across archetypes. Aspect-
    level sentiment is recoverable per slot, which unlocks Aspect-
    Based Sentiment Analysis on top of overall sentiment recovery.

Domain narrative: 60 customers leave one review per month for two years,
producing 1,440 review rows. Engagement trajectory drives the band (and
therefore sentiment); the archetype's opener vocabulary plus the band-
driven object/comment vocabulary together carry the signal a classifier
learns. A bag-of-words classifier predicts the segment above chance —
the shipping target is ≥ 0.45 accuracy on a held-out entity split
(chance is 1/3 for three segments).
"""

from plotsim import create


# ── Shared sentiment pools (object + comment slots) ──────────
#
# Object and comment slots are not archetype-distinct: the same phrase
# pools ride under every segment. The band carries the sentiment, not
# the archetype. Promoters, neutrals, and detractors all draw from
# these pools — the trajectory shape just determines how often each
# band gets visited per segment.

_OBJECT_BY_BAND = {
    "low": [
        "the broken release",
        "the buggy app",
        "the half-baked tool",
        "the unreliable platform",
        "the unfinished product",
        "the clunky workflow",
        "the flaky service",
        "the rough dashboard",
        "the messy interface",
        "the unstable build",
        "the underwhelming experience",
        "the disappointing release",
    ],
    "mid": [
        "the platform",
        "the product",
        "the workflow",
        "the service",
        "the dashboard",
        "the tool",
        "the app",
        "the suite",
        "the basic features",
        "the core product",
        "the latest release",
        "the standard build",
    ],
    "high": [
        "the polished platform",
        "the slick product",
        "the smooth workflow",
        "the reliable service",
        "the responsive dashboard",
        "the powerful tool",
        "the elegant app",
        "the full suite",
        "the flagship features",
        "the well-rounded product",
        "the standout release",
        "the rock-solid build",
    ],
}

_COMMENT_BY_BAND = {
    "low": [
        "Not recommended.",
        "Going elsewhere.",
        "Disappointing.",
        "Cancelled.",
        "Hard to recommend.",
        "Avoid.",
        "Not for me.",
        "Skip it.",
        "Look elsewhere.",
        "Pass.",
        "Bad value.",
        "Cannot endorse.",
    ],
    "mid": [
        "It works.",
        "Does the job.",
        "Reasonable value.",
        "Fair price for what you get.",
        "Meets baseline expectations.",
        "Functional enough.",
        "Continues to deliver.",
        "Adequate.",
        "No surprises.",
        "Works as advertised.",
        "Useful for routine work.",
        "Fits the basic use case.",
    ],
    "high": [
        "Highly recommend.",
        "Best in class.",
        "Cannot imagine going back.",
        "A standout in the category.",
        "Renewing for sure.",
        "Top choice.",
        "Strong endorsement.",
        "Excellent value.",
        "Worth every penny.",
        "Five stars.",
        "Easy to recommend.",
        "A winner.",
    ],
}


# ── Cross-segment shared opener pool ────────────────────────
#
# Phrases that are plausibly from any segment — they carry band-sentiment
# but no archetype-style signal. Concatenated into every segment's
# per-band opener pool by ``_lexicon``. Introducing controlled overlap
# here drops bag-of-words classifier accuracy out of the trivially-
# separable range (≥ 0.90) into a pedagogically-interesting band
# (0.65–0.85) while preserving the M12 design: archetype identity still
# concentrates in the per-segment opener pool, but ~25% of rows draw
# from the shared pool so the BOW signal is noisier than M10 / M12.

_SHARED_OPENERS_BY_BAND = {
    "low": [
        "I have run into issues with",
        "I keep finding bugs in",
        "I am not satisfied with",
        "I cannot get behind",
    ],
    "mid": [
        "I am still working with",
        "I have been using",
        "I make use of",
        "I get value from",
    ],
    "high": [
        "I am sold on",
        "I am a fan of",
        "I keep recommending",
        "I am fond of",
    ],
}


# ── Per-archetype opener vocabularies ──────────────────────
#
# Opener is the archetype-distinct slot. The phrasing register encodes
# segment identity: promoters speak in first-person emotional voice,
# neutrals in measured observational voice, detractors in terse blunt
# voice. Within each archetype, the band carries the sentiment (low =
# negative, mid = neutral, high = positive). The shared pool above is
# concatenated into every segment's per-band opener at ``_lexicon``
# time — see _SHARED_OPENERS_BY_BAND for the rationale.

_PROMOTERS_OPENER = {
    "low": [
        "I am disappointed by",
        "I am frustrated with",
        "I am unhappy with",
        "I am underwhelmed by",
        "I cannot get excited about",
        "I keep getting let down by",
        "I am giving up on",
        "I find myself frustrated by",
        "I am sour on",
        "I am soured by",
        "I cannot recommend",
        "I am losing patience with",
    ],
    "mid": [
        "I am using",
        "I am working with",
        "I have settled into",
        "I have gotten used to",
        "I keep using",
        "I rely on",
        "I have adopted",
        "I have stuck with",
        "I have come to use",
        "I have learned",
        "I find myself reaching for",
        "I keep returning to",
    ],
    "high": [
        "I love",
        "I cannot stop recommending",
        "I truly enjoy",
        "I wholeheartedly endorse",
        "I adore",
        "I am thrilled with",
        "I am amazed by",
        "I am blown away by",
        "I rave about",
        "I am delighted by",
        "I cannot get enough of",
        "I sing the praises of",
    ],
}

_NEUTRALS_OPENER = {
    "low": [
        "I noticed problems with",
        "I have concerns about",
        "I had issues with",
        "I ran into trouble with",
        "I encountered friction with",
        "I found shortcomings in",
        "I see gaps in",
        "I take note of issues with",
        "I observed weaknesses in",
        "I am wary of",
        "I have reservations about",
        "I have doubts about",
    ],
    "mid": [
        "I continue to use",
        "I steadily use",
        "I keep coming back to",
        "I routinely access",
        "I stick with",
        "I default to",
        "I check in on",
        "I open up",
        "I make regular use of",
        "I keep tabs on",
        "I regularly open",
        "I consistently choose",
    ],
    "high": [
        "I consistently recommend",
        "I reliably turn to",
        "I steadily endorse",
        "I find real value in",
        "I see clear benefits from",
        "I appreciate",
        "I am satisfied with",
        "I think highly of",
        "I value",
        "I trust",
        "I am pleased with",
        "I am impressed with",
    ],
}

_DETRACTORS_OPENER = {
    "low": [
        "Hate",
        "Cannot stand",
        "Despise",
        "Have given up on",
        "Am done with",
        "Refuse to use",
        "Avoid",
        "Steer clear of",
        "Am moving on from",
        "Am cancelling",
        "Walked away from",
        "Will not touch",
    ],
    "mid": [
        "Tried",
        "Used",
        "Tested",
        "Demoed",
        "Sampled",
        "Checked",
        "Looked at",
        "Worked with",
        "Logged into",
        "Made do with",
        "Got through",
        "Stuck with",
    ],
    "high": [
        "Liked",
        "Enjoyed",
        "Found value in",
        "Was happy with",
        "Appreciated",
        "Was impressed by",
        "Did enjoy",
        "Was pleased with",
        "Had a good time with",
        "Got real value from",
        "Had fun with",
        "Wound up enjoying",
    ],
}


def _lexicon(opener: dict) -> dict:
    """Compose one archetype's lexicon from its per-segment opener pool,
    the cross-segment shared opener pool, and the shared object +
    comment pools.

    Each band's opener list is ``segment-specific phrases first, shared
    phrases second`` — the same order the bundled YAML lays them out, so
    same-seed runs against ``narrative_reviews.yaml`` and
    ``narrative_reviews.py`` produce byte-identical text columns.
    """
    return {
        "opener": {
            band: list(phrases) + list(_SHARED_OPENERS_BY_BAND[band])
            for band, phrases in opener.items()
        },
        "object": _OBJECT_BY_BAND,
        "comment": _COMMENT_BY_BAND,
    }


_PROMOTERS_LEXICON = _lexicon(_PROMOTERS_OPENER)
_NEUTRALS_LEXICON = _lexicon(_NEUTRALS_OPENER)
_DETRACTORS_LEXICON = _lexicon(_DETRACTORS_OPENER)


config = create(
    about="Customer product reviews — narrative text demo",
    unit="customer",
    seed=2026,
    window=("2024-01", "2025-12", "monthly"),
    metrics=[
        {
            "name": "engagement",
            "label": "Customer engagement score",
            "type": "score",
            "polarity": "positive",
        },
    ],
    segments=[
        {
            "name": "promoters",
            "count": 20,
            "archetype": "growth",
            "label": "Promoters — engagement rises over the window",
        },
        {
            "name": "neutrals",
            "count": 20,
            "archetype": "flat",
            "label": "Neutrals — engagement holds flat",
        },
        {
            "name": "detractors",
            "count": 20,
            "archetype": "decline",
            "label": "Detractors — engagement falls over the window",
        },
    ],
    dimensions=[
        {
            "name": "dim_date",
            "per": "period",
            "columns": [
                {"name": "date_key", "type": "id"},
                {"name": "date", "type": "date"},
                {"name": "year", "type": "int"},
                {"name": "month", "type": "int"},
                {"name": "quarter", "type": "int"},
            ],
        },
        {
            "name": "dim_customer",
            "per": "unit",
            "columns": [
                {"name": "customer_id", "type": "id"},
                {"name": "customer_name", "type": "faker.name"},
            ],
        },
    ],
    facts=[
        {
            "name": "fct_reviews",
            "metrics": ["engagement"],
            "columns": [
                {"name": "review_id", "type": "id"},
                {"name": "customer_id", "type": "ref.dim_customer"},
                {"name": "date_key", "type": "ref.dim_date"},
                {"name": "engagement_score", "type": "metric.engagement"},
                {
                    "name": "review_text",
                    "type": "narrative",
                    "template": "{opener} {object}. {comment}",
                    "lexicons": {
                        "promoters": _PROMOTERS_LEXICON,
                        "neutrals": _NEUTRALS_LEXICON,
                        "detractors": _DETRACTORS_LEXICON,
                    },
                },
            ],
        },
    ],
)
