"""Customer reviews — Python-shaped narrative-text template.

This is the ``create(**kwargs)`` mirror of ``narrative_reviews.yaml`` —
both produce identical engine configs given the same seed. Pick whichever
surface fits your workflow:

* ``narrative_reviews.yaml`` for config-as-data fixtures checked into git
* this file for code-shaped configs that compose with regular Python

Showcase template for ``NarrativeSource`` columns:

  * ``fct_reviews.review_text`` is a trajectory- and archetype-driven
    sentence generated by sampling slot phrases from a per-archetype
    lexicon. Each cell is built from
    ``(trajectory_position, archetype, RNG_state)``: same seed →
    byte-identical text.
  * Three segments (``promoters``, ``neutrals``, ``detractors``) ride
    three archetypes (growth / steady / decline). Each segment has its
    own lexicon — promoters skew positive even in the low band,
    detractors skew negative even in the high band, neutrals stay
    measured. This asymmetry is the signal a classifier learns.
  * Phrase pools include intentional overlap between segments — there
    is no one-to-one phrase → segment lookup. The trajectory-band ×
    segment vocabulary distribution is what carries the discriminative
    signal.

Domain narrative: 60 customers leave one review per month for a year,
producing ~720 review rows. Engagement trajectory drives the band; the
segment's lexicon drives the vocabulary. A bag-of-words classifier
trained on the text predicts the segment well above chance — the
shipping target is ≥ 0.55 accuracy on a held-out entity split (chance
is 1/3 for three segments).
"""

from plotsim import create


# ── Lexicons ──────────────────────────────────────────────
#
# Three segments × three slots × three bands × five phrases =
# 135 phrases. Cross-segment overlap is intentional: e.g. "It works."
# appears in both neutral-mid and promoter-low pools. The signal a
# classifier learns is the joint distribution of (segment, band,
# slot, phrase), not a deterministic mapping.

_PROMOTERS_LEXICON = {
    "opener": {
        "low": [
            "I tried",
            "I am still warming up to",
            "Just getting started with",
            "Recently joined",
            "Slowly using",
        ],
        "mid": [
            "I am using",
            "Settled into",
            "Getting real value from",
            "Finally got the hang of",
            "Genuinely rely on",
        ],
        "high": [
            "I love",
            "Cannot stop recommending",
            "Truly enjoy",
            "Wholeheartedly endorse",
            "Adore",
        ],
    },
    "object": {
        "low": [
            "the app",
            "this tool",
            "the experience",
            "the dashboard",
            "the platform",
        ],
        "mid": [
            "the platform",
            "this product",
            "the workflow",
            "the service",
            "the new release",
        ],
        "high": [
            "this product",
            "every feature",
            "the entire suite",
            "the whole experience",
            "the full platform",
        ],
    },
    "comment": {
        "low": [
            "Decent start.",
            "It works.",
            "Promising so far.",
            "Plenty of room to grow.",
            "Optimistic.",
        ],
        "mid": [
            "Solid choice for the price.",
            "Doing what we hoped.",
            "Real productivity wins.",
            "Glad we picked it.",
            "Recommending to peers.",
        ],
        "high": [
            "Highly recommend.",
            "Best in class.",
            "Cannot imagine going back.",
            "A standout in the category.",
            "Renewing for sure.",
        ],
    },
}

_NEUTRALS_LEXICON = {
    "opener": {
        "low": [
            "Started using",
            "Briefly tried",
            "Logged into",
            "Tested out",
            "Sampled",
        ],
        "mid": [
            "Continue to use",
            "Keep coming back to",
            "Steadily using",
            "Stick with",
            "Routinely access",
        ],
        "high": [
            "Reliably use",
            "Regularly turn to",
            "Frequently open",
            "Consistently choose",
            "Default to",
        ],
    },
    "object": {
        "low": [
            "the app",
            "the tool",
            "this offering",
            "the basic plan",
            "the new build",
        ],
        "mid": [
            "the platform",
            "this product",
            "the service",
            "the dashboard",
            "the workflow",
        ],
        "high": [
            "the platform",
            "the full suite",
            "the workflow",
            "the integrated stack",
            "this product",
        ],
    },
    "comment": {
        "low": [
            "Adequate.",
            "Does what it says.",
            "Nothing exceptional.",
            "Functional enough.",
            "Meets baseline expectations.",
        ],
        "mid": [
            "Reasonable value.",
            "Works as advertised.",
            "It works.",
            "Continues to deliver.",
            "Reliable for routine work.",
        ],
        "high": [
            "Dependable.",
            "Steady performer.",
            "No surprises.",
            "Holds up under load.",
            "A safe choice.",
        ],
    },
}

_DETRACTORS_LEXICON = {
    "opener": {
        "low": [
            "Was hopeful for",
            "Briefly tolerated",
            "Reluctantly used",
            "Forced myself through",
            "Gave up on",
        ],
        "mid": [
            "Tried",
            "Made do with",
            "Endured",
            "Limped along with",
            "Worked around",
        ],
        "high": [
            "Briefly liked",
            "Almost recommended",
            "Sometimes appreciated",
            "Occasionally enjoyed",
            "Now and then valued",
        ],
    },
    "object": {
        "low": [
            "this thing",
            "the broken release",
            "the half-baked tool",
            "the buggy app",
            "this disappointment",
        ],
        "mid": [
            "the service",
            "the platform",
            "the workflow",
            "the basic features",
            "the core product",
        ],
        "high": [
            "the product",
            "the better moments",
            "the rare wins",
            "the working pieces",
            "the stable corner",
        ],
    },
    "comment": {
        "low": [
            "Going elsewhere.",
            "Not for me.",
            "Disappointing.",
            "Cancelled.",
            "Cannot recommend.",
        ],
        "mid": [
            "Mediocre.",
            "Falls short.",
            "Underwhelming.",
            "Has issues.",
            "Better options exist.",
        ],
        "high": [
            "Some good days.",
            "Not bad I guess.",
            "Occasionally usable.",
            "Could be worse.",
            "Better than expected at moments.",
        ],
    },
}


config = create(
    about="Customer product reviews — narrative text demo",
    unit="customer",
    seed=2026,
    window=("2024-01", "2025-12", "monthly"),
    metrics=[
        {
            "name": "engagement",
            "label": "Customer engagement score",
            "type": "score",
            "polarity": "positive",
        },
    ],
    segments=[
        {
            "name": "promoters",
            "count": 20,
            "archetype": "growth",
            "label": "Promoters — engagement rises over the window",
        },
        {
            "name": "neutrals",
            "count": 20,
            "archetype": "flat",
            "label": "Neutrals — engagement holds flat",
        },
        {
            "name": "detractors",
            "count": 20,
            "archetype": "decline",
            "label": "Detractors — engagement falls over the window",
        },
    ],
    dimensions=[
        {
            "name": "dim_date",
            "per": "period",
            "columns": [
                {"name": "date_key", "type": "id"},
                {"name": "date", "type": "date"},
                {"name": "year", "type": "int"},
                {"name": "month", "type": "int"},
                {"name": "quarter", "type": "int"},
            ],
        },
        {
            "name": "dim_customer",
            "per": "unit",
            "columns": [
                {"name": "customer_id", "type": "id"},
                {"name": "customer_name", "type": "faker.name"},
            ],
        },
    ],
    facts=[
        {
            "name": "fct_reviews",
            "metrics": ["engagement"],
            "columns": [
                {"name": "review_id", "type": "id"},
                {"name": "customer_id", "type": "ref.dim_customer"},
                {"name": "date_key", "type": "ref.dim_date"},
                {"name": "engagement_score", "type": "metric.engagement"},
                {
                    "name": "review_text",
                    "type": "narrative",
                    "template": "{opener} {object}. {comment}",
                    "lexicons": {
                        "promoters": _PROMOTERS_LEXICON,
                        "neutrals": _NEUTRALS_LEXICON,
                        "detractors": _DETRACTORS_LEXICON,
                    },
                },
            ],
        },
    ],
)
